In [1]:
#Import modules

import pandas as pd
# from IPython.display import display, HTML
# from numpy import log10, nan, inf, random, clip, arange

# path = './../export_france/data/type1/DP1610_MAASTRICHT1_1997_2013'

# display(HTML("<style>.container { width:100% !important; }</style>"))

import matplotlib.pyplot as plt
%matplotlib inline

import dask.dataframe as dd
from dask.diagnostics import ProgressBar

from numpy import arange, log10

In [2]:
def chunk(s):
    '''
    The function applied to the
    individual partition (map)
    '''    
    return s.apply(lambda x: list(set(x)))


def agg(s):
    '''
    The function whic will aggrgate 
    the result from all the partitions(reduce)
    '''
    s = s._selected_obj    
    return s.groupby(level=list(range(s.index.nlevels))).sum()


def finalize(s):
    '''
    The optional functional that will be 
    applied to the result of the agg_tu functions
    '''
    return s.apply(lambda x: len(set(x)))

tunique = dd.Aggregation('tunique', chunk, agg,finalize)

In [3]:
# dd.read_csv('2014-*.csv')

# drive_path = './../export_france/data/type1/DP1610_MAASTRICHT1_1997_2013'
drive_path = './../../../../media/miglesia/Elements/export_france/data/type1/DP1610_MAASTRICHT1_1997_2013'

n_bins = 20
df_list = n_bins * [ 0 ]

for dataset_i in range(n_bins):
    df_list[dataset_i] = dd.read_csv(drive_path+'/samplings/YMxpb_size20'+str(dataset_i).zfill(2)+'.csv',
                                    usecols = ['YEAR','ID','VAT','CN ID 8', 'VART_sum'])

In [4]:
data = dd.concat(df_list[8:])
data = data.groupby(['YEAR','ID', 'VAT', 'CN ID 8'])['VART_sum'].sum().reset_index()

In [5]:
with ProgressBar():
    out = data.compute()

data = dd.from_pandas(out, npartitions = 500)

[########################################] | 100% Completed |  1min 20.5s

In [6]:
df = data.compute()

In [7]:
grouped = df.groupby(['YEAR', 'ID'])
margins_df = grouped.agg({'VAT': 'nunique', 'CN ID 8': 'nunique'}).add_suffix('_nunique')

margins_df['density'] = grouped.count().iloc[:, 1] / (margins_df['CN ID 8_nunique']*margins_df['VAT_nunique'])
margins_df['avg_x'] = grouped['VART_sum'].mean()
margins_df['sum_x'] = grouped['VART_sum'].sum()

In [8]:
margins_table = margins_df.unstack().swaplevel(axis = 1).sort_index(axis = 1)
margins_table

ID         3110                                                       \
     CN ID 8_nunique VAT_nunique         avg_x   density       sum_x
YEAR
1997            16.0        13.0  7.829975e+05  0.355769  57941812.0
1998            20.0        10.0  6.824995e+05  0.420000  57329954.0
1999            21.0         8.0  8.731745e+05  0.511905  75093005.0
2000            23.0         8.0  8.516883e+05  0.489130  76651943.0
2001            22.0         8.0  5.118489e+05  0.539773  48625642.0
2002            22.0         8.0  1.075843e+06  0.352273  66702292.0
2003            18.0         7.0  1.209340e+06  0.523810  79816472.0
2004            19.0         9.0  1.150132e+06  0.403509  79359101.0
2005            16.0        10.0  1.367636e+06  0.368750  80690497.0
2006            16.0         9.0  1.409259e+06  0.402778  81737049.0
2007            16.0         9.0  1.872838e+06  0.305556  82404851.0
2008            15.0         8.0  2.421284e+06  0.283333  82323672.0
2009            15.0         6.0  2.725835e+06  0.311111  76323387.0
2010            10.0         7.0  3.688968e+06  0.300000  77468328.0
2011            12.0         6.0  2.377333e+06  0.347222  59433325.0
2012             6.0         6.0  2.776349e+05  0.472222   4719793.0
2013            11.0        11.0  1.026297e+06  0.363636  45157069.0

ID         4878                                                        \
     CN ID 8_nunique VAT_nunique          avg_x   density       sum_x
YEAR
1997             2.0        54.0  549978.290909  0.509259  30248806.0
1998             1.0        51.0  907915.176471  1.000000  46303674.0
1999             2.0        51.0  729055.230769  0.509804  37910872.0
2000             1.0        62.0  609310.403226  1.000000  37777245.0
2001             1.0        62.0  776828.354839  1.000000  48163358.0
2002             1.0        75.0  720633.480000  1.000000  54047511.0
2003             7.0        82.0  657402.477273  0.153310  57851418.0
2004             8.0        86.0  590054.576087  0.133721  54285021.0
2005            12.0        88.0  410363.896226  0.100379  43498573.0
2006             5.0        84.0  454622.595506  0.211905  40461411.0
2007             1.0        88.0  646639.318182  1.000000  56904260.0
2008             1.0       109.0  684409.880734  1.000000  74600677.0
2009             NaN         NaN            NaN       NaN         NaN
2010             NaN         NaN            NaN       NaN         NaN
2011             NaN         NaN            NaN       NaN         NaN
2012             4.0        81.0  371741.153846  0.280864  33828445.0
2013             7.0        83.0  740797.649485  0.166954  71857372.0

ID       ...           998269211                                       \
         ...     CN ID 8_nunique VAT_nunique          avg_x   density
YEAR     ...
1997     ...                32.0        99.0  147545.593640  0.089331
1998     ...                28.0        79.0  233539.530303  0.089512
1999     ...                20.0        33.0  419040.157407  0.163636
2000     ...                16.0        32.0  424460.268519  0.210938
2001     ...                11.0        23.0  209847.676768  0.391304
2002     ...                12.0        28.0  240493.202020  0.294643
2003     ...                 9.0        33.0  266875.481132  0.356902
2004     ...                12.0        50.0  205472.620253  0.263333
2005     ...                10.0        34.0  252548.442748  0.385294
2006     ...                10.0        37.0  317755.808824  0.367568
2007     ...                10.0        34.0  388035.434783  0.338235
2008     ...                10.0        31.0  394992.363636  0.354839
2009     ...                 9.0        40.0  249603.007353  0.377778
2010     ...                 9.0        42.0  271971.726027  0.386243
2011     ...                10.0        36.0  316348.983607  0.338889
2012     ...                11.0        29.0  366685.027778  0.338558
2013     ...                10.0        27.0  547182.617647  0.377778

ID                     999990583                                       \
           sum_x CN ID 8_nunique VAT_nunique          avg_x   density
YEAR
1997  41755403.0            19.0        67.0  323186.530612  0.076984
1998  46240827.0            16.0        75.0  242059.392523  0.089167
1999  45256337.0            14.0        72.0  222080.728070  0.113095
2000  45841709.0            14.0        63.0  346586.583333  0.095238
2001  20774920.0            11.0        64.0  387439.111111  0.115057
2002  23808827.0             NaN         NaN            NaN       NaN
2003  28288801.0             NaN         NaN            NaN       NaN
2004  32464674.0             NaN         NaN            NaN       NaN
2005  33083846.0             NaN         NaN            NaN       NaN
2006  43214790.0             NaN         NaN            NaN       NaN
2007  44624075.0             NaN         NaN            NaN       NaN
2008  43449160.0             NaN         NaN            NaN       NaN
2009  33946009.0             NaN         NaN            NaN       NaN
2010  39707872.0             NaN         NaN            NaN       NaN
2011  38594576.0             NaN         NaN            NaN       NaN
2012  39601983.0             NaN         NaN            NaN       NaN
2013  55812627.0             NaN         NaN            NaN       NaN

ID
           sum_x
YEAR
1997  31672280.0
1998  25900355.0
1999  25317203.0
2000  29113273.0
2001  31382568.0
2002         NaN
2003         NaN
2004         NaN
2005         NaN
2006         NaN
2007         NaN
2008         NaN
2009         NaN
2010         NaN
2011         NaN
2012         NaN
2013         NaN

[17 rows x 8115 columns]

In [9]:
log_growth_margins_table = log10(margins_table).diff()
log_growth_margins_table

ID         3110                                                 \
     CN ID 8_nunique VAT_nunique     avg_x   density     sum_x
YEAR
1997             NaN         NaN       NaN       NaN       NaN
1998        0.096910   -0.113943 -0.059658  0.072081 -0.004610
1999        0.021189   -0.096910  0.106999  0.085940  0.117218
2000        0.039509    0.000000 -0.010820 -0.019764  0.008924
2001       -0.019305    0.000000 -0.221139  0.042786 -0.197658
2002        0.000000    0.000000  0.322607 -0.185332  0.137275
2003       -0.087150   -0.057992  0.050800  0.172294  0.077952
2004        0.023481    0.109144 -0.021801 -0.113320 -0.002496
2005       -0.074634    0.045757  0.075223 -0.039121  0.007226
2006        0.000000   -0.045757  0.013021  0.038333  0.005597
2007        0.000000    0.000000  0.123509 -0.119975  0.003534
2008       -0.028029   -0.051153  0.111546 -0.032793 -0.000428
2009        0.000000   -0.124939  0.051454  0.040618 -0.032867
2010       -0.176091    0.066947  0.131405 -0.015794  0.006467
2011        0.079181   -0.066947 -0.190815  0.063486 -0.115094
2012       -0.301030    0.000000 -0.932616  0.133539 -1.100107
2013        0.263241    0.263241  0.567799 -0.113479  0.980803

ID         4878                                                   ...     \
     CN ID 8_nunique VAT_nunique     avg_x   density     sum_x    ...
YEAR                                                              ...
1997             NaN         NaN       NaN       NaN       NaN    ...
1998       -0.301030   -0.024824  0.217700  0.293061  0.184907    ...
1999        0.301030    0.000000 -0.095285 -0.292597 -0.086852    ...
2000       -0.301030    0.084822 -0.077922  0.292597 -0.001533    ...
2001        0.000000    0.000000  0.105486  0.000000  0.105486    ...
2002        0.000000    0.082670 -0.032611  0.000000  0.050059    ...
2003        0.845098    0.038753 -0.039883 -0.814429  0.029538    ...
2004        0.057992    0.020685 -0.046939 -0.059371 -0.027634    ...
2005        0.176091    0.009984 -0.157723 -0.124557 -0.096205    ...
2006       -0.380211   -0.020203  0.044482  0.324499 -0.031434    ...
2007       -0.698970    0.020203  0.153011  0.673859  0.148104    ...
2008        0.000000    0.092944  0.024654  0.000000  0.117598    ...
2009             NaN         NaN       NaN       NaN       NaN    ...
2010             NaN         NaN       NaN       NaN       NaN    ...
2011             NaN         NaN       NaN       NaN       NaN    ...
2012             NaN         NaN       NaN       NaN       NaN    ...
2013        0.243038    0.010593  0.299459 -0.225901  0.327189    ...

ID         998269211                                            \
     CN ID 8_nunique VAT_nunique     avg_x   density     sum_x
YEAR
1997             NaN         NaN       NaN       NaN       NaN
1998       -0.057992   -0.098008  0.199434  0.000879  0.044313
1999       -0.146128   -0.379113  0.253895  0.262000 -0.009346
2000       -0.096910   -0.013364  0.005581  0.110274  0.005581
2001       -0.162727   -0.143422 -0.305933  0.268361 -0.343721
2002        0.037789    0.085430  0.059199 -0.123219  0.059199
2003       -0.124939    0.071356  0.045206  0.083253  0.074877
2004        0.124939    0.180456 -0.113555 -0.132044  0.059797
2005       -0.079181   -0.167491  0.089591  0.165287  0.008205
2006        0.000000    0.036723  0.099749 -0.020455  0.116016
2007        0.000000   -0.036723  0.086778 -0.036118  0.013937
2008        0.000000   -0.040117  0.007717  0.020812 -0.011588
2009       -0.045757    0.110698 -0.199339  0.027205 -0.107193
2010        0.000000    0.021189  0.037274  0.009625  0.068088
2011        0.045757   -0.066947  0.065643 -0.056804 -0.012350
2012        0.041393   -0.093905  0.064127 -0.000424  0.011191
2013       -0.041393   -0.031034  0.173839  0.047603  0.149016

ID         999990583
     CN ID 8_nunique VAT_nunique     avg_x   density     sum_x
YEAR
1997             NaN         NaN       NaN       NaN       NaN
1998       -0.074634    0.048986 -0.125531  0.063805 -0.087374
1999       -0.057992   -0.017729 -0.037411  0.103242 -0.009890
2000        0.000000   -0.057992  0.193301 -0.074634  0.060675
2001       -0.104735    0.006839  0.048392  0.082102  0.032597
2002             NaN         NaN       NaN       NaN       NaN
2003             NaN         NaN       NaN       NaN       NaN
2004             NaN         NaN       NaN       NaN       NaN
2005             NaN         NaN       NaN       NaN       NaN
2006             NaN         NaN       NaN       NaN       NaN
2007             NaN         NaN       NaN       NaN       NaN
2008             NaN         NaN       NaN       NaN       NaN
2009             NaN         NaN       NaN       NaN       NaN
2010             NaN         NaN       NaN       NaN       NaN
2011             NaN         NaN       NaN       NaN       NaN
2012             NaN         NaN       NaN       NaN       NaN
2013             NaN         NaN       NaN       NaN       NaN

[17 rows x 8115 columns]

In [10]:
# pd.DataFrame(log_growth_margins_table.mean()).unstack().sort_values(by = (0, 'sum_x'))
pd.DataFrame(log_growth_margins_table.mean()).reset_index().groupby('level_1')[0].describe()

,count,mean,std,min,25%,50%,75%,max
level_1,,,,,,,,
CN ID 8_nunique,1539.0,0.001536,0.094990,-1.493358,-0.024871,0.000000,0.025188,0.903090
VAT_nunique,1539.0,-0.001687,0.111392,-1.176091,-0.023827,0.001322,0.028938,0.922385
avg_x,1539.0,0.007779,0.173845,-3.762189,-0.027019,0.010309,0.047137,1.526510
density,1539.0,0.003075,0.064365,-0.497325,-0.018229,0.000000,0.022685,0.693034
sum_x,1539.0,0.010703,0.249447,-3.762189,-0.022689,0.016794,0.055742,2.371608

In [11]:
# firm_sizes = log10(data.groupby(['ID', 'YEAR'])['VART_sum'].sum().reset_index().groupby('ID')[['VART_sum']].mean().compute())