# Data reading and sampling

In [1]:
import pandas as pd
import numpy as np
import time

### Useful functions for chunk filtering and aggregation

In [2]:

path = './../../../../media/miglesia/Elements/export_france/data/'
path1 = path+'type1/DP1610_MAASTRICHT1_1997_2013'
path2 = path+'type2/DP1611_MAASTRICHT2_1997_2013'

# Writing as a function

def aggregation(chunk, index, func):
    grouped_object = chunk.groupby(index,sort = False)
    # not sorting results in a minor speedup
    return grouped_object.agg(func)
                                
colnames = [u'YEAR', u'MONTH', u'FLUX', u'ID', u'DEPT', u'CN ID 8', u'CPA6',
       u'PYOD', u'PAYP', u'VAT', u'PRIFAC', u'DEVFAC', u'VFTE', u'VART', u'D_MASSE', u'MASSE', u'USUP', u'USUP_MT']

colname_no = dict(zip(colnames, range(18)))
colno_name = dict(zip(range(18), colnames))

#We need to know number of rows of each file:

l = []
with open(path+'/type1_row_ct') as f:
    for line in f:
        l += [int(line.strip())]
nrows1 = dict(zip(range(1997, 2014), l))

l = []
with open(path+'/type2_row_ct') as f:
    for line in f:
        l += [int(line.strip())]
nrows2 = dict(zip(range(1997, 2014), l))

def merge_ref(df, filter_ref, filter_ix):
    return df.reset_index().merge(filter_ref, on = filter_ix, how = 'left').set_index('index')
     
def select_entries(df, filter_col, value, by_df = None):
    if by_df is None:
        by_df = df
        
    if isinstance(value, (list,)):
        return df.loc[by_df[filter_col].isin(value)]
    else:
        return df.loc[by_df[filter_col] == value]

### Load and process references for filtering (eg. data on firm sizes to filter by size)

In [3]:

sizes_index = pd.read_csv('./../export_france/data/formatted/sizes_index.csv')

n_bins = 20

sizes_index['log_exp_mma'] = np.log10(sizes_index.exp_mma).round(3)
cuts = pd.cut(sizes_index.groupby(sizes_index['log_exp_mma']).sum().cumsum()['exp_mma'],n_bins, labels=range(n_bins))
exp_index = sizes_index.merge(cuts.reset_index().rename({'exp_mma': 'exp_mma_cat'}, axis = 1), on = 'log_exp_mma').dropna(subset = ['exp_mma'])

exp_size_ref = exp_index[['ID', 'exp_mma_cat']]; filter_ix = 'ID'; filter_col = 'exp_mma_cat';

In [1]:
colname_no

NameError: name 'colname_no' is not defined

### Main loop for reading from hard drive and saving

In [4]:
# names = tuple(index)
# sampling_name = name

years = list(reversed(range(1997, 2014)))
n_chunks = 5
data_path = path+'type1/DP1610_MAASTRICHT1_1997_2013'
columns = ['YEAR', 'MONTH', 'FLUX', 'ID', 'CN ID 8', 'VAT','VART']
aggregate_chunks = True
chunk_agg_func = {'VART':['sum']}
aggregate_years = True
yr_agg_func = {'VART_sum':['sum']}
verbose = True
output_index = ['YEAR', 'MONTH', 'IMPORT', 'ID', 'CN ID 8', 'VAT']

save_yr_agg_result = True
save_path = path1+'/samplings'

for bin_ in list(reversed(range(5))): #n_bins
    print 'bin no. '+str(bin_)
    sampling_name = 'YMxpb_size'+str(n_bins).zfill(2)+str(bin_).zfill(2)
    l = []

    for y in years:
        print 'year: '+str(y)
        #Rows for each chunk
        size = np.ceil(nrows1[y]/n_chunks)
        print 'max_chunk_size: '+str(size)

        reader = pd.read_csv(data_path+'/DP1610_MAASTRICHT1_'+str(y)+'.txt', chunksize = size, 
                             usecols = map(colname_no.get, columns)
                             , delimiter = ';', header = None) #'CN ID 8', 'PYOD'

        yr_result_list = []

        #Loop over chunks
        for i in range(int(n_chunks)):
            start_time = time.time()
            chunk = next(reader).rename(colno_name, axis = 1)
            chunk['IMPORT'] = chunk['FLUX'] % 2 # so that '1' indicates imports

            """
            Chunk filtering
            """
            #select imports/exports
            chunk = select_entries(chunk, filter_col = 'IMPORT', value = 0)

            # select by firm size
            chunk_ = merge_ref(chunk, exp_size_ref, filter_ix = 'ID')
            chunk = select_entries(chunk, filter_col = 'exp_mma_cat', value = bin_, by_df = chunk_)

            """
            Chunk aggregation
            """
            if aggregate_chunks: 
                result_chunk = aggregation(chunk, output_index, chunk_agg_func)
            else: 
                result_chunk = chunk

    #             print result_chunk.head()

            yr_result_list += [result_chunk]
            if verbose: print("Number of rows ",result_chunk.shape[0])
            if verbose: print("Loop ",i,"took %s seconds" % (time.time() - start_time))
            del(result_chunk) 


        concat_result = pd.concat(yr_result_list)
    #         print concat_result.head()

        # Unique users vs Number of rows after the first computation    
        if verbose: print("size of concat_result:", len(concat_result))
    #         if verbose: print("unique firms in concat_result:", len(concat_result.index.unique()))

        result = concat_result
        result.columns = ['_'.join(col).strip() for col in result.columns.values]

        if aggregate_years:
    #             yr_agg_result = result.groupby(index).agg(yr_agg_func)
            yr_agg_result = aggregation(result, output_index, yr_agg_func)
            yr_agg_result.index = pd.MultiIndex.from_tuples(list(yr_agg_result.index), names=tuple(output_index))
            yr_agg_result.columns = yr_agg_result.columns.droplevel(1)

        else:
            yr_agg_result = result

        if verbose: print("size of yr_agg_result:", len(yr_agg_result))

        l += [yr_agg_result]

        if save_yr_agg_result:
            yr_agg_result.to_csv(save_path+'/'+sampling_name+'_'+str(y)+'.csv')

    filename = save_path+'/'+sampling_name+'.csv'
    pd.concat(l).to_csv(filename, index = True)
    print 'saved at: '+str(filename)

bin no. 4
year: 2013
max_chunk_size: 8180411.0
('Number of rows ', 302642)
('Loop ', 0, 'took 13.9477069378 seconds')
('Number of rows ', 393928)
('Loop ', 1, 'took 14.4318678379 seconds')
('Number of rows ', 341081)
('Loop ', 2, 'took 13.6467909813 seconds')
('Number of rows ', 293679)
('Loop ', 3, 'took 13.7152709961 seconds')
('Number of rows ', 438088)
('Loop ', 4, 'took 15.204102993 seconds')
('size of concat_result:', 1769418)
('size of yr_agg_result:', 1769418)
year: 2012
max_chunk_size: 7662320.0
('Number of rows ', 327518)
('Loop ', 0, 'took 13.8196032047 seconds')
('Number of rows ', 409615)
('Loop ', 1, 'took 12.7951090336 seconds')
('Number of rows ', 356790)
('Loop ', 2, 'took 13.3200321198 seconds')
('Number of rows ', 300242)
('Loop ', 3, 'took 11.6757600307 seconds')
('Number of rows ', 443861)
('Loop ', 4, 'took 13.136922121 seconds')
('size of concat_result:', 1838026)
('size of yr_agg_result:', 1838026)
year: 2011
max_chunk_size: 7195973.0
('Number of rows ', 329935)
('Loop ', 0, 'took 12.0339870453 seconds')
('Number of rows ', 412061)
('Loop ', 1, 'took 11.9617278576 seconds')
('Number of rows ', 367878)
('Loop ', 2, 'took 11.936798811 seconds')
('Number of rows ', 333353)
('Loop ', 3, 'took 11.8032450676 seconds')
('Number of rows ', 443877)
('Loop ', 4, 'took 12.0782859325 seconds')
('size of concat_result:', 1887104)
('size of yr_agg_result:', 1887104)
year: 2010
max_chunk_size: 6993649.0
('Number of rows ', 318639)
('Loop ', 0, 'took 12.6183290482 seconds')
('Number of rows ', 432627)
('Loop ', 1, 'took 12.7147080898 seconds')
('Number of rows ', 356639)
('Loop ', 2, 'took 12.7117030621 seconds')
('Number of rows ', 337937)
('Loop ', 3, 'took 11.614082098 seconds')
('Number of rows ', 458697)
('Loop ', 4, 'took 12.3916378021 seconds')
('size of concat_result:', 1904539)
('size of yr_agg_result:', 1904539)
year: 2009
max_chunk_size: 6278669.0
('Number of rows ', 323112)
('Loop ', 0, 'took 10.7770211697 seconds')
('Number of rows ', 395642)
('Loop ', 1, 'took 10.9725039005 seconds')
('Number of rows ', 351607)
('Loop ', 2, 'took 11.0192620754 seconds')
('Number of rows ', 325143)
('Loop ', 3, 'took 10.1357550621 seconds')
('Number of rows ', 432166)
('Loop ', 4, 'took 11.3840408325 seconds')
('size of concat_result:', 1827670)
('size of yr_agg_result:', 1827670)
year: 2008
max_chunk_size: 6309116.0
('Number of rows ', 348349)
('Loop ', 0, 'took 11.1269631386 seconds')
('Number of rows ', 371911)
('Loop ', 1, 'took 11.9650540352 seconds')
('Number of rows ', 403101)
('Loop ', 2, 'took 12.4559371471 seconds')
('Number of rows ', 326730)
('Loop ', 3, 'took 11.3746831417 seconds')
('Number of rows ', 451503)
('Loop ', 4, 'took 12.5259389877 seconds')
('size of concat_result:', 1901594)
('size of yr_agg_result:', 1901594)
year: 2007
max_chunk_size: 6160497.0
('Number of rows ', 316790)
('Loop ', 0, 'took 13.4012131691 seconds')
('Number of rows ', 407608)
('Loop ', 1, 'took 12.1931509972 seconds')
('Number of rows ', 351376)
('Loop ', 2, 'took 12.0405380726 seconds')
('Number of rows ', 318711)
('Loop ', 3, 'took 11.3904690742 seconds')
('Number of rows ', 444418)
('Loop ', 4, 'took 12.8067948818 seconds')
('size of concat_result:', 1838903)
('size of yr_agg_result:', 1838903)
year: 2006
max_chunk_size: 5789960.0
('Number of rows ', 276557)
('Loop ', 0, 'took 11.4449188709 seconds')
('Number of rows ', 363951)
('Loop ', 1, 'took 11.1819610596 seconds')
('Number of rows ', 325295)
('Loop ', 2, 'took 11.6386890411 seconds')
('Number of rows ', 317130)
('Loop ', 3, 'took 10.9012269974 seconds')
('Number of rows ', 404811)
('Loop ', 4, 'took 11.5697219372 seconds')
('size of concat_result:', 1687744)
('size of yr_agg_result:', 1687744)
year: 2005
max_chunk_size: 5559688.0
('Number of rows ', 233331)
('Loop ', 0, 'took 10.3111281395 seconds')
('Number of rows ', 318215)
('Loop ', 1, 'took 10.7330999374 seconds')
('Number of rows ', 290698)
('Loop ', 2, 'took 10.4331109524 seconds')
('Number of rows ', 277013)
('Loop ', 3, 'took 10.4156620502 seconds')
('Number of rows ', 369947)
('Loop ', 4, 'took 11.3115620613 seconds')
('size of concat_result:', 1489204)
('size of yr_agg_result:', 1489204)
year: 2004
max_chunk_size: 5218704.0
('Number of rows ', 248532)
('Loop ', 0, 'took 10.4328539371 seconds')
('Number of rows ', 305272)
('Loop ', 1, 'took 10.0867381096 seconds')
('Number of rows ', 270831)
('Loop ', 2, 'took 10.2905631065 seconds')
('Number of rows ', 264595)
('Loop ', 3, 'took 10.1605591774 seconds')
('Number of rows ', 300643)
('Loop ', 4, 'took 12.3875908852 seconds')
('size of concat_result:', 1389873)
('size of yr_agg_result:', 1389873)
year: 2003
max_chunk_size: 4899719.0
('Number of rows ', 255630)
('Loop ', 0, 'took 9.8306479454 seconds')
('Number of rows ', 273732)
('Loop ', 1, 'took 10.2486979961 seconds')
('Number of rows ', 266819)
('Loop ', 2, 'took 10.1792390347 seconds')
('Number of rows ', 230060)
('Loop ', 3, 'took 9.34922409058 seconds')
('Number of rows ', 295797)
('Loop ', 4, 'took 9.93997812271 seconds')
('size of concat_result:', 1322038)
('size of yr_agg_result:', 1322038)
year: 2002
max_chunk_size: 4739381.0
('Number of rows ', 235318)
('Loop ', 0, 'took 9.82677221298 seconds')
('Number of rows ', 270112)
('Loop ', 1, 'took 9.76036500931 seconds')
('Number of rows ', 266659)
('Loop ', 2, 'took 9.37001490593 seconds')
('Number of rows ', 237125)
('Loop ', 3, 'took 9.07592511177 seconds')
('Number of rows ', 291830)
('Loop ', 4, 'took 9.91286182404 seconds')
('size of concat_result:', 1301044)
('size of yr_agg_result:', 1301044)
year: 2001
max_chunk_size: 4634439.0
('Number of rows ', 238120)
('Loop ', 0, 'took 9.96439599991 seconds')
('Number of rows ', 256318)
('Loop ', 1, 'took 9.29551696777 seconds')
('Number of rows ', 274263)
('Loop ', 2, 'took 9.69497895241 seconds')
('Number of rows ', 228270)
('Loop ', 3, 'took 8.67206692696 seconds')
('Number of rows ', 287187)
('Loop ', 4, 'took 10.1295468807 seconds')
('size of concat_result:', 1284158)
('size of yr_agg_result:', 1284158)
year: 2000
max_chunk_size: 4608999.0
('Number of rows ', 235606)
('Loop ', 0, 'took 9.30647516251 seconds')
('Number of rows ', 256080)
('Loop ', 1, 'took 9.20810699463 seconds')
('Number of rows ', 255444)
('Loop ', 2, 'took 9.26107215881 seconds')
('Number of rows ', 228006)
('Loop ', 3, 'took 8.68952512741 seconds')
('Number of rows ', 279021)
('Loop ', 4, 'took 9.32705307007 seconds')
('size of concat_result:', 1254157)
('size of yr_agg_result:', 1254157)
year: 1999
max_chunk_size: 4400886.0
('Number of rows ', 229672)
('Loop ', 0, 'took 9.05083799362 seconds')
('Number of rows ', 263043)
('Loop ', 1, 'took 8.72825479507 seconds')
('Number of rows ', 237553)
('Loop ', 2, 'took 8.88780283928 seconds')
('Number of rows ', 236569)
('Loop ', 3, 'took 7.92498111725 seconds')
('Number of rows ', 262581)
('Loop ', 4, 'took 28.3624939919 seconds')
('size of concat_result:', 1229418)
('size of yr_agg_result:', 1229418)
year: 1998
max_chunk_size: 4181341.0
('Number of rows ', 214444)
('Loop ', 0, 'took 7.44507098198 seconds')
('Number of rows ', 243977)
('Loop ', 1, 'took 7.23466897011 seconds')
('Number of rows ', 232266)
('Loop ', 2, 'took 7.34340691566 seconds')
('Number of rows ', 220787)
('Loop ', 3, 'took 7.42842411995 seconds')
('Number of rows ', 249680)
('Loop ', 4, 'took 8.39774703979 seconds')
('size of concat_result:', 1161154)
('size of yr_agg_result:', 1161154)
year: 1997
max_chunk_size: 3860625.0
('Number of rows ', 181260)
('Loop ', 0, 'took 6.70360684395 seconds')
('Number of rows ', 227940)
('Loop ', 1, 'took 6.78444385529 seconds')
('Number of rows ', 195056)
('Loop ', 2, 'took 7.15361881256 seconds')
('Number of rows ', 195081)
('Loop ', 3, 'took 6.71233201027 seconds')
('Number of rows ', 227168)
('Loop ', 4, 'took 6.84835410118 seconds')
('size of concat_result:', 1026505)
('size of yr_agg_result:', 1026505)
saved at: ./../../../../media/miglesia/Elements/export_france/data/type1/DP1610_MAASTRICHT1_1997_2013/samplings/YMxpb_size2004.csv
bin no. 3
year: 2013
max_chunk_size: 8180411.0
('Number of rows ', 267201)
('Loop ', 0, 'took 13.7272500992 seconds')
('Number of rows ', 343072)
('Loop ', 1, 'took 12.6762878895 seconds')
('Number of rows ', 288919)
('Loop ', 2, 'took 12.9357988834 seconds')
('Number of rows ', 245402)
('Loop ', 3, 'took 12.6043550968 seconds')
('Number of rows ', 372618)
('Loop ', 4, 'took 13.4965929985 seconds')
('size of concat_result:', 1517212)
('size of yr_agg_result:', 1517212)
year: 2012
max_chunk_size: 7662320.0
('Number of rows ', 270721)
('Loop ', 0, 'took 12.0424470901 seconds')
('Number of rows ', 340682)
('Loop ', 1, 'took 12.0376739502 seconds')
('Number of rows ', 290274)
('Loop ', 2, 'took 12.3371109962 seconds')
('Number of rows ', 246709)
('Loop ', 3, 'took 11.332665205 seconds')
('Number of rows ', 368031)
('Loop ', 4, 'took 12.5590829849 seconds')
('size of concat_result:', 1516417)
('size of yr_agg_result:', 1516417)
year: 2011
max_chunk_size: 7195973.0
('Number of rows ', 278175)
('Loop ', 0, 'took 11.2788350582 seconds')
('Number of rows ', 340164)
('Loop ', 1, 'took 11.3182199001 seconds')
('Number of rows ', 302931)
('Loop ', 2, 'took 11.7510139942 seconds')
('Number of rows ', 270344)
('Loop ', 3, 'took 10.8120849133 seconds')
('Number of rows ', 368040)
('Loop ', 4, 'took 11.4093949795 seconds')
('size of concat_result:', 1559654)
('size of yr_agg_result:', 1559654)
year: 2010
max_chunk_size: 6993649.0
('Number of rows ', 264484)
('Loop ', 0, 'took 11.6926450729 seconds')
('Number of rows ', 365248)
('Loop ', 1, 'took 13.1544401646 seconds')
('Number of rows ', 283536)
('Loop ', 2, 'took 12.1003260612 seconds')
('Number of rows ', 272148)
('Loop ', 3, 'took 10.9837300777 seconds')
('Number of rows ', 375104)
('Loop ', 4, 'took 11.8111650944 seconds')
('size of concat_result:', 1560520)
('size of yr_agg_result:', 1560520)
year: 2009
max_chunk_size: 6278669.0
('Number of rows ', 268386)
('Loop ', 0, 'took 10.2598609924 seconds')
('Number of rows ', 319434)
('Loop ', 1, 'took 10.5645420551 seconds')
('Number of rows ', 279617)
('Loop ', 2, 'took 10.2514541149 seconds')
('Number of rows ', 274940)
('Loop ', 3, 'took 9.8309109211 seconds')
('Number of rows ', 332609)
('Loop ', 4, 'took 10.6702809334 seconds')
('size of concat_result:', 1474986)
('size of yr_agg_result:', 1474986)
year: 2008
max_chunk_size: 6309116.0
('Number of rows ', 302509)
('Loop ', 0, 'took 10.5696160793 seconds')
('Number of rows ', 318684)
('Loop ', 1, 'took 14.1679589748 seconds')
('Number of rows ', 336197)
('Loop ', 2, 'took 10.8097348213 seconds')
('Number of rows ', 274989)
('Loop ', 3, 'took 10.1111729145 seconds')
('Number of rows ', 356950)
('Loop ', 4, 'took 10.9352369308 seconds')
('size of concat_result:', 1589329)
('size of yr_agg_result:', 1589329)
year: 2007
max_chunk_size: 6160497.0
('Number of rows ', 275541)
('Loop ', 0, 'took 10.39534688 seconds')
('Number of rows ', 350999)
('Loop ', 1, 'took 10.3417928219 seconds')
('Number of rows ', 294224)
('Loop ', 2, 'took 10.061496973 seconds')
('Number of rows ', 282013)
('Loop ', 3, 'took 9.8209631443 seconds')
('Number of rows ', 371677)
('Loop ', 4, 'took 10.6431131363 seconds')
('size of concat_result:', 1574454)
('size of yr_agg_result:', 1574454)
year: 2006
max_chunk_size: 5789960.0
('Number of rows ', 267289)
('Loop ', 0, 'took 10.3975479603 seconds')
('Number of rows ', 341883)
('Loop ', 1, 'took 9.97214603424 seconds')
('Number of rows ', 291380)
('Loop ', 2, 'took 10.2618980408 seconds')
('Number of rows ', 300179)
('Loop ', 3, 'took 9.57839393616 seconds')
('Number of rows ', 351077)
('Loop ', 4, 'took 9.91428780556 seconds')
('size of concat_result:', 1551808)
('size of yr_agg_result:', 1551808)
year: 2005
max_chunk_size: 5559688.0
('Number of rows ', 259076)
('Loop ', 0, 'took 9.05098700523 seconds')
('Number of rows ', 337614)
('Loop ', 1, 'took 9.39578390121 seconds')
('Number of rows ', 291208)
('Loop ', 2, 'took 9.18743300438 seconds')
('Number of rows ', 283452)
('Loop ', 3, 'took 9.13854789734 seconds')
('Number of rows ', 350607)
('Loop ', 4, 'took 9.53771901131 seconds')
('size of concat_result:', 1521957)
('size of yr_agg_result:', 1521957)
year: 2004
max_chunk_size: 5218704.0
('Number of rows ', 247209)
('Loop ', 0, 'took 8.63054680824 seconds')
('Number of rows ', 316964)
('Loop ', 1, 'took 8.79503703117 seconds')
('Number of rows ', 272786)
('Loop ', 2, 'took 9.02286291122 seconds')
('Number of rows ', 281200)
('Loop ', 3, 'took 8.75066113472 seconds')
('Number of rows ', 324354)
('Loop ', 4, 'took 9.14877390862 seconds')
('size of concat_result:', 1442513)
('size of yr_agg_result:', 1442513)
year: 2003
max_chunk_size: 4899719.0
('Number of rows ', 240291)
('Loop ', 0, 'took 8.18458986282 seconds')
('Number of rows ', 284579)
('Loop ', 1, 'took 8.24977898598 seconds')
('Number of rows ', 278103)
('Loop ', 2, 'took 8.67640805244 seconds')
('Number of rows ', 238213)
('Loop ', 3, 'took 8.3927218914 seconds')
('Number of rows ', 321676)
('Loop ', 4, 'took 8.48198103905 seconds')
('size of concat_result:', 1362862)
('size of yr_agg_result:', 1362862)
year: 2002
max_chunk_size: 4739381.0
('Number of rows ', 226992)
('Loop ', 0, 'took 8.28378009796 seconds')
('Number of rows ', 279632)
('Loop ', 1, 'took 8.33422994614 seconds')
('Number of rows ', 263848)
('Loop ', 2, 'took 8.17145299911 seconds')
('Number of rows ', 220775)
('Loop ', 3, 'took 7.78389000893 seconds')
('Number of rows ', 312675)
('Loop ', 4, 'took 8.6497220993 seconds')
('size of concat_result:', 1303922)
('size of yr_agg_result:', 1303922)
year: 2001
max_chunk_size: 4634439.0
('Number of rows ', 223731)
('Loop ', 0, 'took 8.10240507126 seconds')
('Number of rows ', 260628)
('Loop ', 1, 'took 8.34812092781 seconds')
('Number of rows ', 273927)
('Loop ', 2, 'took 8.12891197205 seconds')
('Number of rows ', 216953)
('Loop ', 3, 'took 7.73528599739 seconds')
('Number of rows ', 306017)
('Loop ', 4, 'took 8.03918290138 seconds')
('size of concat_result:', 1281256)
('size of yr_agg_result:', 1281256)
year: 2000
max_chunk_size: 4608999.0
('Number of rows ', 218762)
('Loop ', 0, 'took 8.17592811584 seconds')
('Number of rows ', 266356)
('Loop ', 1, 'took 7.85202598572 seconds')
('Number of rows ', 259903)
('Loop ', 2, 'took 7.74863100052 seconds')
('Number of rows ', 215571)
('Loop ', 3, 'took 7.31607484818 seconds')
('Number of rows ', 306689)
('Loop ', 4, 'took 8.05688691139 seconds')
('size of concat_result:', 1267281)
('size of yr_agg_result:', 1267281)
year: 1999
max_chunk_size: 4400886.0
('Number of rows ', 196140)
('Loop ', 0, 'took 7.62975811958 seconds')
('Number of rows ', 257634)
('Loop ', 1, 'took 7.62228512764 seconds')
('Number of rows ', 228094)
('Loop ', 2, 'took 7.65020608902 seconds')
('Number of rows ', 218627)
('Loop ', 3, 'took 7.19626808167 seconds')
('Number of rows ', 269663)
('Loop ', 4, 'took 7.71574401855 seconds')
('size of concat_result:', 1170158)
('size of yr_agg_result:', 1170158)
year: 1998
max_chunk_size: 4181341.0
('Number of rows ', 189861)
('Loop ', 0, 'took 6.99265909195 seconds')
('Number of rows ', 241952)
('Loop ', 1, 'took 7.2383518219 seconds')
('Number of rows ', 222670)
('Loop ', 2, 'took 7.13760995865 seconds')
('Number of rows ', 190470)
('Loop ', 3, 'took 7.07163691521 seconds')
('Number of rows ', 264266)
('Loop ', 4, 'took 7.39826607704 seconds')
('size of concat_result:', 1109219)
('size of yr_agg_result:', 1109219)
year: 1997
max_chunk_size: 3860625.0
('Number of rows ', 169348)
('Loop ', 0, 'took 6.36749601364 seconds')
('Number of rows ', 221568)
('Loop ', 1, 'took 6.63799309731 seconds')
('Number of rows ', 196715)
('Loop ', 2, 'took 6.88196396828 seconds')
('Number of rows ', 183893)
('Loop ', 3, 'took 6.64007496834 seconds')
('Number of rows ', 229306)
('Loop ', 4, 'took 6.75161099434 seconds')
('size of concat_result:', 1000830)
('size of yr_agg_result:', 1000830)
saved at: ./../../../../media/miglesia/Elements/export_france/data/type1/DP1610_MAASTRICHT1_1997_2013/samplings/YMxpb_size2003.csv
bin no. 2
year: 2013
max_chunk_size: 8180411.0
('Number of rows ', 275174)
('Loop ', 0, 'took 12.4316511154 seconds')
('Number of rows ', 375949)
('Loop ', 1, 'took 14.1992459297 seconds')
('Number of rows ', 315724)
('Loop ', 2, 'took 13.2213308811 seconds')
('Number of rows ', 271477)
('Loop ', 3, 'took 12.524597168 seconds')
('Number of rows ', 431653)
('Loop ', 4, 'took 13.5490601063 seconds')
('size of concat_result:', 1669977)
('size of yr_agg_result:', 1669977)
year: 2012
max_chunk_size: 7662320.0
('Number of rows ', 274601)
('Loop ', 0, 'took 12.2138729095 seconds')
('Number of rows ', 369071)
('Loop ', 1, 'took 12.0638329983 seconds')
('Number of rows ', 309960)
('Loop ', 2, 'took 12.2787089348 seconds')
('Number of rows ', 263312)
('Loop ', 3, 'took 11.332983017 seconds')
('Number of rows ', 423996)
('Loop ', 4, 'took 12.3244009018 seconds')
('size of concat_result:', 1640940)
('size of yr_agg_result:', 1640940)
year: 2011
max_chunk_size: 7195973.0
('Number of rows ', 264167)
('Loop ', 0, 'took 11.1698520184 seconds')
('Number of rows ', 355330)
('Loop ', 1, 'took 11.097728014 seconds')
('Number of rows ', 306916)
('Loop ', 2, 'took 11.7191560268 seconds')
('Number of rows ', 272422)
('Loop ', 3, 'took 10.9187939167 seconds')
('Number of rows ', 398876)
('Loop ', 4, 'took 11.6250169277 seconds')
('size of concat_result:', 1597711)
('size of yr_agg_result:', 1597711)
year: 2010
max_chunk_size: 6993649.0
('Number of rows ', 258481)
('Loop ', 0, 'took 11.2102079391 seconds')
('Number of rows ', 375431)
('Loop ', 1, 'took 11.9662358761 seconds')
('Number of rows ', 290903)
('Loop ', 2, 'took 11.9215669632 seconds')
('Number of rows ', 281282)
('Loop ', 3, 'took 11.1030030251 seconds')
('Number of rows ', 397056)
('Loop ', 4, 'took 11.9332430363 seconds')
('size of concat_result:', 1603153)
('size of yr_agg_result:', 1603153)
year: 2009
max_chunk_size: 6278669.0
('Number of rows ', 261395)
('Loop ', 0, 'took 10.0685532093 seconds')
('Number of rows ', 348545)
('Loop ', 1, 'took 10.2579479218 seconds')
('Number of rows ', 292250)
('Loop ', 2, 'took 10.5717420578 seconds')
('Number of rows ', 282011)
('Loop ', 3, 'took 9.99090003967 seconds')
('Number of rows ', 372574)
('Loop ', 4, 'took 10.7710959911 seconds')
('size of concat_result:', 1556775)
('size of yr_agg_result:', 1556775)
year: 2008
max_chunk_size: 6309116.0
('Number of rows ', 285232)
('Loop ', 0, 'took 10.5561378002 seconds')
('Number of rows ', 316633)
('Loop ', 1, 'took 10.2730391026 seconds')
('Number of rows ', 349524)
('Loop ', 2, 'took 11.0022301674 seconds')
('Number of rows ', 265820)
('Loop ', 3, 'took 9.96272993088 seconds')
('Number of rows ', 401000)
('Loop ', 4, 'took 10.964815855 seconds')
('size of concat_result:', 1618209)
('size of yr_agg_result:', 1618209)
year: 2007
max_chunk_size: 6160497.0
('Number of rows ', 275037)
('Loop ', 0, 'took 10.3407030106 seconds')
('Number of rows ', 365500)
('Loop ', 1, 'took 11.0996658802 seconds')
('Number of rows ', 305728)
('Loop ', 2, 'took 9.91721487045 seconds')
('Number of rows ', 273330)
('Loop ', 3, 'took 9.64201402664 seconds')
('Number of rows ', 414859)
('Loop ', 4, 'took 10.8362979889 seconds')
('size of concat_result:', 1634454)
('size of yr_agg_result:', 1634454)
year: 2006
max_chunk_size: 5789960.0
('Number of rows ', 251066)
('Loop ', 0, 'took 9.78657698631 seconds')
('Number of rows ', 336653)
('Loop ', 1, 'took 10.0127820969 seconds')
('Number of rows ', 285973)
('Loop ', 2, 'took 10.2363801003 seconds')
('Number of rows ', 267971)
('Loop ', 3, 'took 9.37937092781 seconds')
('Number of rows ', 383036)
('Loop ', 4, 'took 10.0318188667 seconds')
('size of concat_result:', 1524699)
('size of yr_agg_result:', 1524699)
year: 2005
max_chunk_size: 5559688.0
('Number of rows ', 240111)
('Loop ', 0, 'took 9.08154296875 seconds')
('Number of rows ', 332796)
('Loop ', 1, 'took 9.48034596443 seconds')
('Number of rows ', 280186)

/home/miglesia/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2825: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

In [5]:
# # Imports and exports by firm/year

# IDs = firm_stats['ID']
# Mns = [1, 2, 3]

# def sample_data(columns, index = ['ID', 'IMPORT','YEAR'], chunk_agg = True, chunk_agg_func = {}, 
#             yr_agg_func = {}, name = 'test_sampling', n_chunks = 30.,
#                 firm_filtering = True, firm_filtering_cols = ['ID'], firm_filtering_arrays = [IDs],
#                 time_filtering = False, time_filtering_arrays = [Mns],
#                 verbose = False, yr_chunks_agg = True, save_yr_agg_result = False,
#                data_path = path1, save_path = path1+'/samplings/', select_IMPORTS = None):

#     names = tuple(index)
#     sampling_name = name

#     l = []

#     for y in years:
#         print 'year: '+str(y)
#         #Rows for each chunk
#         size = np.ceil(nrows1[y]/n_chunks)
#         print 'max_chunk_size: '+str(size)

#         reader = pd.read_csv(data_path+'/DP1610_MAASTRICHT1_'+str(y)+'.txt', chunksize = size, 
#                              usecols = map(colname_no.get, columns)
#                              , delimiter = ';', header = None) #'CN ID 8', 'PYOD'

#         yr_result_list = []

#         for i in range(int(n_chunks)):
#             start_time = time.time()
#             chunk = next(reader).rename(colno_name, axis = 1)
#             chunk['IMPORT'] = chunk['FLUX'] % 2 # so that '1' indicates imports
# #             print chunk.head()

#             if firm_filtering == True:
#                 for i in range(len(firm_filtering_cols)):
#                     chunk = chunk.loc[chunk[firm_filtering_cols[i]].isin(firm_filtering_arrays[i])]
#                     print 'filtered_chunk_size: '+str(len(chunk))
# #             print chunk.head()
                    
#             if time_filtering == True:
#                 time_filtering_cols = ['MONTH']
#                 for i in range(len(time_filtering_cols)):
#                     chunk = chunk.loc[chunk[time_filtering_cols[i]].isin(time_filtering_arrays[i])]
#                     print 'filtered_chunk_size: '+str(len(chunk))

#             if select_IMPORTS != None: chunk = chunk.loc[chunk.IMPORT == select_IMPORTS]

#             if chunk_agg: 
#                 result_chunk = aggregation(chunk, index, chunk_agg_func)
#             else: 
#                 result_chunk = chunk
                
# #             print result_chunk.head()

#             yr_result_list += [result_chunk]
#             if verbose: print("Number of rows ",result_chunk.shape[0])
#             if verbose: print("Loop ",i,"took %s seconds" % (time.time() - start_time))
#             del(result_chunk) 


#         concat_result = pd.concat(yr_result_list)
# #         print concat_result.head()
        
#         # Unique users vs Number of rows after the first computation    
#         if verbose: print("size of concat_result:", len(concat_result))
# #         if verbose: print("unique firms in concat_result:", len(concat_result.index.unique()))

#         result = concat_result
#         result.columns = ['_'.join(col).strip() for col in result.columns.values]

#         if yr_chunks_agg:
# #             yr_agg_result = result.groupby(index).agg(yr_agg_func)
#             yr_agg_result = aggregation(result, index, yr_agg_func)
#             yr_agg_result.index = pd.MultiIndex.from_tuples(list(yr_agg_result.index), names=names)
#             yr_agg_result.columns = yr_agg_result.columns.droplevel(1)

#         else:
#             yr_agg_result = result

#         if verbose: print("size of yr_agg_result:", len(yr_agg_result))

#         l += [yr_agg_result]

#         if save_yr_agg_result:
#             yr_agg_result.to_csv(save_path+'/'+sampling_name+'_'+str(y)+'.csv')
    
#     filename = save_path+'/'+sampling_name+'.csv'
#     pd.concat(l).to_csv(filename, index = True)
#     print 'saved at: '+str(filename)

In [6]:
# sizes_index = pd.read_csv('./../export_france/data/formatted/sizes_index.csv')

# n = 10

# sizes_index['log_exp_mma'] = np.log10(sizes_index.exp_mma).round(3)
# cuts = pd.cut(sizes_index.groupby(sizes_index['log_exp_mma']).sum().cumsum()['exp_mma'],n, labels=range(n))
# exp_index = sizes_index.merge(cuts.reset_index().rename({'exp_mma': 'exp_mma_cat'}, axis = 1), on = 'log_exp_mma').dropna(subset = ['exp_mma'])

In [7]:
# # Oct 4
# sizes_index = pd.read_csv('./../export_france/data/formatted/sizes_index.csv', index_col=0)
# n = 20
# exp_index = sizes_index.dropna(subset = ['exp_mma'])
# exp_index['exp_qcut_'+str(n)+'_label'] = pd.qcut(exp_index['exp_mma'], n, labels=range(n))
# exp_index['exp_qcut_'+str(n)] = pd.qcut(exp_index['exp_mma'], n)

# # imp_index = sizes_index.dropna(subset = ['imp_mma'])
# # imp_index['imp_cut_'+str(n)+'_label'] = pd.cut(imp_index['imp_mma'], n, labels=range(n))
# # imp_index['imp_cut_'+str(n)] = pd.cut(imp_index['imp_mma'], n)

In [8]:

# Mns = range(1,13)
# time_filtering_arrays = [Mns]

# # use all firms
# sample_n_firms = 'max'

# years = list(reversed(range(1997, 2014)))

# for bin_label in list(reversed(range(n))):
#     print 'bin label: '+str(bin_label)
#     IDs = exp_index.loc[exp_index.exp_mma_cat == bin_label].index
#     print IDs
# #     IDs = imp_index.loc[imp_index.imp_cut_20_label == bin_label].index
#     columns = ['YEAR', 'MONTH', 'FLUX', 'ID', 'CN ID 8', 'VAT','VART']
#     sample_data(columns, index = ['YEAR', 'MONTH', 'IMPORT', 'ID', 'CN ID 8', 'VAT'], chunk_agg_func = {'VART':['sum']}, 
#                 firm_filtering = True, firm_filtering_cols = ['ID'], firm_filtering_arrays = [IDs],
#                 yr_agg_func = {'VART_sum':['sum']}, n_chunks = 10., 
#                 name = 'firm_sample_YMxpb_n'+str(n).zfill(2)+str(bin_label).zfill(2),
#                 verbose = False, yr_chunks_agg = True, select_IMPORTS = 0, save_yr_agg_result = True)